/**
 * Configuration options for X-Sign-Payload
 */
export interface XSignConfig {
  /** Secret key for signing/verification */
  secret: string;
  /** Algorithm: 'sha256' or 'sha512' */
  algorithm?: "sha256" | "sha512";
  /** Enable timestamp for replay protection */
  enableTimestamp?: boolean;
  /** Replay window in minutes */
  replayWindow?: number;
}

/**
 * Headers generated by signing
 */
export interface XSignHeaders {
  [key: string]: string | undefined;
  "X-Signature": string;
  "X-Timestamp"?: string;
  "Content-Type": string;
}

/**
 * Sign method options
 */
export interface SignOptions {
  /** Custom timestamp (ms since epoch). Auto-generated if not provided */
  timestamp?: number;
  /** Override config for this sign operation */
  algorithm?: "sha256" | "sha512";
}

/**
 * Verify method options
 */
export interface VerifyOptions {
  /** Expected signature format: 'sha256=...' or 'sha512=...' */
  signature: string;
  /** Request body as string */
  body: string;
  /** Timestamp header value */
  timestamp?: string;
}

/**
 * Result of a signing operation
 */
export interface SignResult {
  headers: XSignHeaders;
  signature: string;
  timestamp?: string;
}
